spring:
    devtools:
        restart:
            exclude: static/**,public/**

logging:
    level:
        org:
            hibernate:
                SQL: debug
                type:
                    descripter:
                        sql:
                            BasicBinder: trace
                    EnumType: trace